// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5DNfMXCumIVLqAlf8_Pq4DaTGmzRfgk',
    appId: '1:630625944745:android:6d4eaa89afc54bde84d5b8',
    messagingSenderId: '630625944745',
    projectId: 'smartspend-22',
    storageBucket: 'smartspend-22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAph-CqOTaFL-nRNmf45eMA0-ERoZyW7MQ',
    appId: '1:630625944745:ios:ebb3f0d9de5625ed84d5b8',
    messagingSenderId: '630625944745',
    projectId: 'smartspend-22',
    storageBucket: 'smartspend-22.firebasestorage.app',
    iosClientId: '630625944745-gd13c9it2liusembp35g8afmnc10lm2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartspend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCag6ZfCPFwurj8IJDzcjPlqee68aaprfg',
    appId: '1:630625944745:web:e8263facc009834384d5b8',
    messagingSenderId: '630625944745',
    projectId: 'smartspend-22',
    authDomain: 'smartspend-22.firebaseapp.com',
    storageBucket: 'smartspend-22.firebasestorage.app',
    measurementId: 'G-N0YBRPH1P5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCag6ZfCPFwurj8IJDzcjPlqee68aaprfg',
    appId: '1:630625944745:web:25ba6734fa3e0d9284d5b8',
    messagingSenderId: '630625944745',
    projectId: 'smartspend-22',
    authDomain: 'smartspend-22.firebaseapp.com',
    storageBucket: 'smartspend-22.firebasestorage.app',
    measurementId: 'G-HQV8TMSWG3',
  );

}